### PR TITLE
add support for chrf++ metric 

### PR DESCRIPTION
**Pull request by gwenzek**
For the WMT22 shared task, we want to use Chrf++ as a metric to evaluate the translation instead of spBLEU like last year.

@vedanuj can you confirm this is the correct way of computing Chrf++ (In particular we don't explicitly do tokenization) ?

@TristanThrush can you help me figure out if this is the only thing that need to be added for new metrics ?

When creating a new task Dynabench seems to compare the "perf_metric" to a list of accepted metrics. Where is this list ?
Does that mean we need to upgrade Dynabench before I can create the new task ?

### CODE REVIEW

**Comment by gwenzek** [comment]
recheck

**Comment by gwenzek** [comment]
recheck

**Comment by gwenzek** [comment]
Hi, can someone retrigger the integration tests ? I've received the email saying my CLA has been validated,
and the bot also says "MLCommons CLA bot All contributors have signed the MLCommons CLA" 

But the tests results are still the one from yesterday

**Comment by douwekiela** [comment]
Seems to pass now?

**Comment by gwenzek** [comment]
yes, I had to trigger the build by collapsing the two previous commits. I think it's ready to merge.

**Pull request merged**
