### PR TITLE
Update UserLeaderBoardCSV.tsx

### PR DESCRIPTION
**Pull request by Alicia-Parrish**
Change the name of the leaderboard from "Example Leaderboard" to "Validated Attack Success Rate"

### CODE REVIEW

**Comment by Alicia-Parrish** [comment]
I filled out the google form to be added to the CLA.

**Comment by Ciroye** [comment]
Perfect, LGTM, we only need to wait until MLCommons approved the CLA

**Comment by Alicia-Parrish** [comment]
recheck

**Comment by Ciroye** [comment]
Hi @Alicia-Parrish, Since the idea is that other challenges can use the same components we implemented a different way in which we use that YAML file. With this implementation if you need to change the title you only need to change your yaml file

https://github.com/mlcommons/dynabench/blob/main/frontends/web/src/new_front/components/Tables/Leaderboard/UserLeaderBoardCSV.tsx#L10.

**Pull request closed without merging**
